### ISSUE TITLE
Problems in compiling to Raspberry Pi via the package on PyPi, libblepp compilation

### ISSUE THREAD

**Issue by amarchino** [mbientlab/PyWarble#2]
Greetings!

This issue follows mbientlab/PyWarble#1 in that it's a compilation error following the resolution of the other issue. 
By using pip to compile the upstream Metawear-SDK-Python on a Raspberry Pi 3 B+, we found a problem in compiling the Warble package, as uploaded on PyPi.

By use of `pip` to compile the upstream package, we found that the creation of the libble++ library throws an error since it tries to compile with the -m64 option, which on the Raspberry Pi is not defined.
This seems to be caused by the fact that the dependency on libblepp includes an already configured Makefile, which was made for a x86-64 architecture.

As before, we ask for Your help in building Your library for use as dependency of other packages.

We attach to this issue the compilation log and the Makefile found in the PyPi package. (The Makefile had to be renamed to Makefile.txt so as to circumvent the limitations of the file upload on GitHub)
[compilation_error.txt](https://github.com/mbientlab/PyWarble/files/2132289/compilation_error.txt)
[Makefile](https://github.com/mbientlab/PyWarble/files/2132294/Makefile.txt)

Thanks

**Comment by scaryghost** [comment]
Fixed in v1.0.7

**Comment by amarchino** [comment]
It now seems to work correctly.
Thanks for your hard word!
